services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data

  app:
    build: .
    container_name: spring-app
    depends_on:
      - rabbit-mq
      - db
      - redis
    ports:
      - "8080:8080"
      - "9091:9091"
    env_file: .env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafanadata:/var/lib/grafana

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.6.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - promtail-data:/var/lib/promtail
      - ./promtail.yaml:/etc/promtail/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

  loki:
    image: grafana/loki:3.6.7
    container_name: loki
    restart: unless-stopped
    volumes:
      - loki-data:/var/lib/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    command:
      - --config.file=/etc/loki/loki-config.yaml

volumes:
  pgdata:
  redisdata:
  grafanadata:
  prometheus-data:
  rabbitmq-data:
  promtail-data:
  loki-data:
